name: order-generator
services:
  rabbitmq:
    container_name: rabbitmq-producer
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: defaultUser
      RABBITMQ_DEFAULT_PASS: defaultPass
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_producer
    volumes:
      - rabbitmq_producer_data:/var/lib/rrabbitmq

volumes:
  rabbitmq_producer_data:

networks:
  rabbitmq_producer: